### ISSUE TITLE
Raspberry Pi files?

### ISSUE THREAD

**Issue by jmfloyd** [wagiminator/ATtiny13-TinyUPS#1]
Stefan,

Your readme suggests that there should be some RaspberryPi scripts to monitor the UPS and an install shell script to set them up.  They seem to have been lost.

I followed your advice to get the board(s) made and mostly populated.  Nearly ready to test the setup.

Cheers
John

**Comment by wagiminator** [comment]
Hi John, 
oops, you're right. I have no idea how that happened. I uploaded the scripts again. 
Greetings, Stefan

**Comment by jmfloyd** [comment]
Thanks JohnOn Dec 1, 2021 4:21 PM, Stefan Wagner ***@***.***> wrote:
Hi John,
oops, you're right. I have no idea how that happened. I uploaded the scripts again.
Greetings, Stefan
